services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html:ro
    depends_on:
      - wordpress
      - static
    networks:
      - inception

  redis:
    build:
      context: ./requirements/bonus/redis
    image: redis
    container_name: redis
    restart: always
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - inception

  static:
    build: ./requirements/bonus/static
    image: static
    container_name: static
    restart: always
    networks:
      - inception

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mmaltas-/data/mariadb

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mmaltas-/data/wordpress

networks:
  inception:
    name: inception-network
    driver: bridge
